version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ec2-user/cicd-python-project-01/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
    - location: scripts/start_application.sh
      timeout: 300
