version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - mkdir -p build  # Create the build directory
      - echo Build completed on `date`
      # Add commands here to generate output files in the build/ directory
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: build/  # Ensure this directory is created and populated
