version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application...
      - mkdir -p build  # Create a build directory if it doesn't exist
      - cp -r * build/  # Copy all files to the build directory (adjust as needed)
      - cd build
      - zip -r ../my_application.zip .  # Create a ZIP file of the build directory contents
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - my_application.zip  # Specify the ZIP file as an artifact
